### PR TITLE
Add social authentication

### PR DESCRIPTION
**Pull request by mwinel**
#### What does this PR do?
This PR adds the social authentication feature. A user can either signup or login with social auth.

#### Description of Task to be completed

1. Add facebook social authentication.
2. Add google social authentication.

#### How should this be manually tested?

1. clone the repo
2. run `npm install`
3. run `npm start`
4. signup on `http://localhost:3000/signup`
5. login on `http://localhost:3000/login`

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#165273434](https://www.pivotaltracker.com/story/show/165273434)
#### Screenshots (if appropriate)
N/A

### CODE REVIEW

**Comment by KabohaJeanMark** [comment]
Great job Nelson. I have tried this out and like how I have been able to log in to our Author's Haven with my google account.

**Comment by sanya-kenneth** [comment]
Good work Nelson. I have tested the social authentication feature and I was able to signup and login using google. However I think it would be nice if you styled up the social authentication buttons a little more so that they blend with the pages. You could refer to the screenshot below. 

Screenshot 2019-06-13 at 10 52 45

**Comment by sanya-kenneth** [comment]
I also tried to signup and login with facebook but I wasn't able to. Could you kindly fix this so that users are able to login and signup using facebook.

**Comment by sanya-kenneth** [comment]
Could you also be able to add the signup and login with twitter feature so that users are able to signup and login with twitter?

**Comment by 3Nakajugo** [comment]
Great work @Nelson, I was able to login with google but not with Facebook.
image

**Comment by engjames** [comment]
Thanks, Nelson for the good work though am getting this error when I try to login using google
image

**Review by KabohaJeanMark — COMMENTED** [review]
Good job Nelson. I can now log in through both google and facebook.

**Review by KabohaJeanMark — APPROVED** [review]

**Review by KabohaJeanMark — COMMENTED** [review]
The social login through facebook and google works quite well on the [review app](https://staging-f-invictus-pr-21.herokuapp.com/)

**Review by njeri-ngigi — APPROVED** [review]
Good job

**Pull request merged**
